/**
 * Title: Even Fibonacci numbers
 * <p>
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Problem2 {
    public int solve() {
        int previous = 1;
        int current = 1;
        int result = 0;

        while (current <= 4000000) {
            if (current % 2 == 0) {
                result += current;
            }
            int newCurrent = current + previous;
            previous = current;
            current = newCurrent;
        }
        return result;
    }

    public static void main(String[] args) {
        int result = new Problem2().solve();
        System.out.println("Result: " + result);
    }
}
